pages:
  - 主页: 'index.md'
  - 入门(Getting started):
    - OpenGL: '01 Getting started/01 OpenGL.md'
    - 创建一个窗口: '01 Getting started/02 Creating a window.md'
    - Hello Window: '01 Getting started/03 Hello Window.md'
    - Hello Triangle: '01 Getting started/04 Hello Triangle.md'
    - 着色器: '01 Getting started/05 Shaders.md'
    - 纹理: '01 Getting started/06 Textures.md'
    - 变换: '01 Getting started/07 Transformations.md'
    - 坐标系统: '01 Getting started/08 Coordinate Systems.md'
    - 摄像机: '01 Getting started/09 Camera.md'
    - 复习: '01 Getting started/10 Review.md'
  - 光照(Lighting):
    - 颜色: '02 Lighting/01 Colors.md'
    - 基本光源: '02 Lighting/02 Basic Lighting.md'
    - 材质: '02 Lighting/03 Materials.md'
    - 光照贴图: '02 Lighting/04 Lighting maps.md'
    - 投光物: '02 Lighting/05 Light casters.md'
    - 多光源: '02 Lighting/06 Multiple lights.md'
    - 复习: '02 Lighting/07 Review.md'
  - 加载模型(Model Loading):
    - Assimp: '03 Model Loading/01 Assimp.md'
    - 网格: '03 Model Loading/02 Mesh.md'
    - 模型: '03 Model Loading/03 Model.md'
  - 高级OpenGL(Advanced OpenGL):
    - 深度测试: '04 Advanced OpenGL/01 Depth testing.md'
    - 模板测试: '04 Advanced OpenGL/02 Stencil testing.md'
    - 混合: '04 Advanced OpenGL/03 Blending.md'
    - 面剔除: '04 Advanced OpenGL/04 Face culling.md'
    - 帧缓冲: '04 Advanced OpenGL/05 Framebuffers.md'
    - Cubmaps: '04 Advanced OpenGL/06 Cubemaps.md'
    - 高级数据: '04 Advanced OpenGL/07 Advanced Data.md'
    - 高级GLSL: '04 Advanced OpenGL/08 Advanced GLSL.md'
    - 几何着色器: '04 Advanced OpenGL/09 Geometry Shader.md'
    - 实例化: '04 Advanced OpenGL/10 Instancing.md'
    - 反走样: '04 Advanced OpenGL/11 Anti Aliasing.md'
  - 高级光照(Advanced Lighting):
    - HDR: '05 Advanced Lighting/06 HDR.md'

site_name: LearnOpenGL-CN

markdown_extensions:
  - admonition
  - smarty
  - sane_lists

extra_css:
  - css/code_fixer.css
